services:
  - type: web
    name: flask-contact-api
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: EMAIL_TO
        sync: false
